#! /bin/sh
LD_LIBRARY_PATH=/opt/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
BIN=/opt/bin/squeezelite-i386
NAME=ds214play
stop(){
  pid=`ps -ef | grep squeezelite-i386 | grep -v grep | awk '{print $2;}'`
  for p in `echo $pid`
  do
	echo stopping $p
	kill $p
  done
}
if [ "$1" = "start" ]; then
	stop
	echo starting $BIN
	$BIN -n $NAME -s localhost &
	exit 0
fi
if [ "$1" = "stop" ] ; then
	stop
	exit 0
fi
echo "ERROR - only start supported"
exit 1
  
